---
site_name: Palo Alto Networks Policy Orchestration with Ansible
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
  - mkdocstrings
  - autorefs
  - mermaid2

theme:
  name: "material"
  palette:
    primary: black
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.select
  logo: img/icon_white.svg

repo_url: https://github.com/adambaumeister/ansible_panos_policy_orchestration

nav:
  - Introduction: index.md
  - User Guide:
      - Introduction: user_guide/introduction.md
      - Preset Policy: user_guide/preset_policy.md
      - Preset URL Lists: user_guide/preset_policy_urls.md
      - New Policy Creation: user_guide/new_policy_creation.md
      - Testing Security Policies: user_guide/policy_lookup.md
  - Reference:
      - policy_creation Role: reference/policy_creation_role.md
      - New Policy Tasks:
          - lookup_policy.yml: reference/lookup_policy.md
          - security_policy_match.yml: reference/security_policy_match.md
          - get_zone_by_ip.yml: reference/get_zone_by_ip.md
          - create_policy.yml: reference/create_policy.md
      - Preset Policy Tasks:
          - add_address_to_preset_group.yml: reference/add_address_to_preset_group.md
          - add_application_to_preset_group.yml: reference/add_application_to_preset_group.md
          - add_url_to_preset_category.yml: reference/add_url_to_preset_category.md
  - Changelog: CHANGELOG.md

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:abaumeister@paloaltonetworks.com
