---
argument_specs:
  main:
    short_description: Configure new network access in Palo Alto Networks Panorama
    description:
      - >-
        The main entry point that includes all tasks.
    options:
      policy_files:
        type: "list"
        elements: "str"
        required: true
        description: "A list of policy files compatible with this role."
        version_added: 1.0.0
      source_user:
        type: "str"
        required: false
        description: "The source user for the new policy"
      source_ip:
        type: "str"
        required: false
        description: "The the source IP for the new policy"
      destination_ip:
        type: "str"
        required: false
        description: "The the destination IP for the new policy"
      application:
        type: "str"
        required: true
        description: "The PAN-OS compatible Application for the policy."
      destination_port:
        type: "str"
        required: true
        description: "The TCP or UDP port used by the traffic in the policy"