---
# Tasks file which adds one (or more) URLs to the given URL category.

- name: Get existing URL CATEGORY objects
  paloaltonetworks.panos.panos_custom_url_category:
    provider: "{{ provider }}"
    device_group: "{{ policy_creation_device_group }}"
    name: "{{ destination_url_category }}"
    state: gathered
  register: policy_creation_existing_group

- name: Add URL to preset URL LIST
  paloaltonetworks.panos.panos_custom_url_category:
    provider: "{{ provider }}"
    device_group: "{{ policy_creation_device_group }}"
    name: "{{ destination_url_category }}"
    url_value: "{{ [url] + policy_creation_existing_group.gathered.url_value }}"
    state: present
  register: policy_creation_group_addition
  when:
    - policy_creation_existing_group.gathered.type == 'URL List'
