---
# This tasks file connects to all the devices in a given device group and attempts to test to see if the traffic is
# Already permitted using "test security-policy-match".
#
# It will also try to enumerate which zones to use when defining new policy.
#
# There are some important assumptions that this playbook makes:
#   1. There is no NAT, or that if there is, it won't impact the logic
#   2. Traffic is not transiting intra-zone (i.e in teh same zone on one interface, out another interface in teh same
#       zone
#   3. We calcualte the zones and the firewalls to test by simply using ALL serial numbers connected to Panormaa. In
#       bigger environments this may be very slow, and you should change the filter to choose a subset either based on
#       the device group, or some other parameter retrievable at runtime
#
# Requires either 'policy_creation_device_group' or 'default_new_policy_device_group' to be set

- name: Populate all facts for policy
  ansible.builtin.set_fact:
    policy_creation_destination_port: "{{ policy_creation_destination_port | default('443') }}"
    policy_creation_protocol: "{{ policy_creation_protocol | default('6') }}"
    policy_creation_application: "{{ policy_creation_application | default('ssl') }}"

- name: Set the operating device group
  ansible.builtin.set_fact:
    _policy_creation_device_group: "{{ policy_creation_device_group }}"
  when:
    - policy_creation_device_group is defined

- name: Set the operating device group
  ansible.builtin.set_fact:
    _policy_creation_device_group: "{{ default_new_policy_device_group }}"
  when:
    - default_new_policy_device_group is defined

- name: Get device for testing block
  block:
    - name: Get all connected devices
      paloaltonetworks.panos.panos_op:
        provider: "{{ provider }}"
        cmd: "show devices connected"
      register: policy_creation__show_devices_output

    - name: Set JSON Object for stdout
      ansible.builtin.set_fact:
        policy_creation__show_devices_output_dict: >
          {{ policy_creation__show_devices_output | paloaltonetworks.panos_policy_automation.panos_op_stdout_to_dict }}

    - name: Set the list of items
      ansible.builtin.set_fact:
        policy_creation___device_list: "{{ policy_creation__show_devices_output_dict.response.result.devices.entry }}"

    - name: Set the list of items (if single item response)
      ansible.builtin.set_fact:
        policy_creation___device_list:
          - "{{ policy_creation__show_devices_output_dict.response.result.devices.entry }}"
      when: "policy_creation__show_devices_output_dict.response.result.devices.entry is mapping"
  when: default_test_policy_serial_number is not defined

- name: Set device_list when we have a serial number for all testing
  ansible.builtin.set_fact:
    policy_creation___device_list:
      - serial: "{{ default_test_policy_serial_number }}"
  when: default_test_policy_serial_number is defined

- name: Test the security policy - determines if a new policy is needed
  ansible.builtin.include_tasks:
    file: security_policy_match.yml
  with_items: "{{ policy_creation___device_list }}"

- name: Get the zone for the DESTINATION IP
  ansible.builtin.include_tasks:
    file: get_zone_by_ip.yml
  vars:
    _target_ip: "{{ policy_creation_destination_ip }}"
  with_items: "{{ policy_creation___device_list }}"
  when:
    - not policy_creation_security_matches_existing_policy
